### PR TITLE
Add gallery

### PR DESCRIPTION
**Pull request by szmoon**
Caved and used bulma to make the gallery grid - similar to the search-result-card I'm working on in getty-ui, I'm having trouble working with the getty-ui column content not respecting the boundary of the column. The getty-ui quarter columns also defaulted to 1 item per column on smaller screen sizes, which I thought didn't really work with our use-case here

### CODE REVIEW

**Comment by szmoon** [comment]
@abrin Are we okay with the grid being 3 3 2?
Screen Shot 2020-04-14 at 8 13 47 AM

**Comment by abrin** [comment]
I think so, @kristenGRI ?

**Comment by szmoon** [comment]
@abrin @kristenGRI I think it depends on how we want to display the QR code image when a gallery image is clicked - in my first pass I had the rows stay as 4 and 4 because I didn't think the pixelated image needed to be too large, even on a phone, plus it gave room for you to see the output of the click without scrolling. But definitely open to other solutions!

**Comment by abrin** [comment]
Screen Shot 2020-04-14 at 8 26 15 AM

adjusted

**Pull request merged**
